### ISSUE TITLE
Crash on Api 23

### ISSUE THREAD

**Issue by felipe9962** [alphacep/vosk-android-demo#133]
Hi, if u execute the demo in API 23 the app crashes with this error:

`E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
    Process: org.vosk.demo, PID: 9455
    java.lang.RuntimeException: An error occurred while executing doInBackground()
        at android.os.AsyncTask$3.done(AsyncTask.java:309)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
        at java.util.concurrent.FutureTask.run(FutureTask.java:242)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at java.lang.Thread.run(Thread.java:818)
     Caused by: java.lang.UnsatisfiedLinkError: Unable to load library 'vosk':
    dlopen failed: cannot locate symbol "fopen64" referenced by "/data/app/org.vosk.demo-1/lib/x86/libvosk.so"...
    dlopen failed: cannot locate symbol "fopen64" referenced by "/data/app/org.vosk.demo-1/lib/x86/libvosk.so"...
    dlopen failed: cannot locate symbol "fopen64" referenced by "/data/app/org.vosk.demo-1/lib/x86/libvosk.so"...
    Native library (android-x86/libvosk.so) not found in resource path (.)
        at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:301)
        at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:461)
        at com.sun.jna.Native.register(Native.java:1746)
        at org.vosk.LibVosk.<clinit>(LibVosk.java:9)
        at org.vosk.demo.VoskActivity$SetupTask.doInBackground(VoskActivity.java:111)
        at org.vosk.demo.VoskActivity$SetupTask.doInBackground(VoskActivity.java:97)
        at android.os.AsyncTask$2.call(AsyncTask.java:295)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        	... 4 more
    	Suppressed: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "fopen64" referenced by "/data/app/org.vosk.demo-1/lib/x86/libvosk.so"...
        at com.sun.jna.Native.open(Native Method)
        at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:191)
        		... 11 more
    	Suppressed: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "fopen64" referenced by "/data/app/org.vosk.demo-1/lib/x86/libvosk.so"...
        at com.sun.jna.Native.open(Native Method)
        at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:204)
        		... 11 more
    	Suppressed: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "fopen64" referenced by "/data/app/org.vosk.demo-1/lib/x86/libvosk.so"...
        at java.lang.Runtime.loadLibrary(Runtime.java:372)
        at java.lang.System.loadLibrary(System.java:1076)
        at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:218)
        		... 11 more
    	Suppressed: java.io.IOException: Native library (android-x86/libvosk.so) not found in resource path (.)
        at com.sun.jna.Native.extractFromResourcePath(Native.java:1119)
        at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:275)
        		... 11 more
D/EGL_emulation: eglMakeCurrent: 0xae514540: ver 2 0 (tinfo 0xae512c40)
E/Surface: getSlotFromBufferLocked: unknown buffer: 0xae689640`

Any ideas?

**Comment by felipe9962** [comment]
@nshmyrev What should I do with what you have coomit me?

**Comment by nshmyrev** [comment]
@felipe9962 I have just pushed an update aar to the maven, check it if fixes your issues.

**Comment by felipe9962** [comment]
Same error: 
E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
    Process: org.vosk.demo, PID: 10263
    java.lang.RuntimeException: An error occurred while executing doInBackground()
        at android.os.AsyncTask$3.done(AsyncTask.java:309)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
        at java.util.concurrent.FutureTask.run(FutureTask.java:242)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at java.lang.Thread.run(Thread.java:818)
     Caused by: java.lang.UnsatisfiedLinkError: Unable to load library 'vosk':
    dlopen failed: cannot locate symbol "fopen64" referenced by "/data/app/org.vosk.demo-2/lib/x86/libvosk.so"...
    dlopen failed: cannot locate symbol "fopen64" referenced by "/data/app/org.vosk.demo-2/lib/x86/libvosk.so"...
    dlopen failed: cannot locate symbol "fopen64" referenced by "/data/app/org.vosk.demo-2/lib/x86/libvosk.so"...
    Native library (android-x86/libvosk.so) not found in resource path (.)
        at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:301)
        at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:461)
        at com.sun.jna.Native.register(Native.java:1746)
        at org.vosk.LibVosk.<clinit>(LibVosk.java:9)
        at org.vosk.demo.VoskActivity$SetupTask.doInBackground(VoskActivity.java:111)
        at org.vosk.demo.VoskActivity$SetupTask.doInBackground(VoskActivity.java:97)
        at android.os.AsyncTask$2.call(AsyncTask.java:295)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        	... 4 more
    	Suppressed: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "fopen64" referenced by "/data/app/org.vosk.demo-2/lib/x86/libvosk.so"...
        at com.sun.jna.Native.open(Native Method)
        at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:191)
        		... 11 more
    	Suppressed: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "fopen64" referenced by "/data/app/org.vosk.demo-2/lib/x86/libvosk.so"...
        at com.sun.jna.Native.open(Native Method)
        at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:204)
        		... 11 more
    	Suppressed: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "fopen64" referenced by "/data/app/org.vosk.demo-2/lib/x86/libvosk.so"...
        at java.lang.Runtime.loadLibrary(Runtime.java:372)
        at java.lang.System.loadLibrary(System.java:1076)
        at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:218)
        		... 11 more
    	Suppressed: java.io.IOException: Native library (android-x86/libvosk.so) not found in resource path (.)
        at com.sun.jna.Native.extractFromResourcePath(Native.java:1119)
        at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:275)
        		... 11 more
D/EGL_emulation: eglMakeCurrent: 0xaa99c480: ver 2 0 (tinfo 0xaa9a2460)
E/Surface: getSlotFromBufferLocked: unknown buffer: 0xb407c760

**Comment by nshmyrev** [comment]
> Same error:

You didn't update properly, check your code uses newer aar from today.

**Comment by felipe9962** [comment]
Yep, now works succesfully, thank you :)
