### ISSUE TITLE
Error while start demo project

### ISSUE THREAD

**Issue by UsovITAD** [alphacep/vosk-android-demo#155]
I got this error while starting a project:
```08-17 19:51:59.296 6059-6059/org.vosk.demo E/art: dlopen("/data/app/org.vosk.demo-2/lib/x86/libvosk.so", RTLD_LAZY) failed: dlopen failed: "/data/app/org.vosk.demo-2/lib/x86/libvosk.so" has unexpected e_machine: 40
08-17 19:51:59.308 6059-6059/org.vosk.demo D/AndroidRuntime: Shutting down VM
08-17 19:51:59.310 6059-6059/org.vosk.demo E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.vosk.demo, PID: 6059
    java.lang.UnsatisfiedLinkError: Unable to load library 'vosk':
    dlopen failed: "libvosk.so" has unexpected e_machine: 40
    dlopen failed: "libvosk.so" has unexpected e_machine: 40
    dlopen failed: "/data/app/org.vosk.demo-2/lib/x86/libvosk.so" has unexpected e_machine: 40
    Native library (android-x86-64/libvosk.so) not found in resource path (.)
        at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:301)
        at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:461)
        at com.sun.jna.Native.register(Native.java:1746)
        at org.vosk.LibVosk.<clinit>(LibVosk.java:9)
        at org.vosk.demo.VoskActivity.onCreate(VoskActivity.java:72)
        at android.app.Activity.performCreate(Activity.java:5994)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
        at android.app.ActivityThread.access$800(ActivityThread.java:151)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5258)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
    	Suppressed: java.lang.UnsatisfiedLinkError: dlopen failed: "libvosk.so" has unexpected e_machine: 40
        at com.sun.jna.Native.open(Native Method)
        at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:191)
        		... 17 more
    	Suppressed: java.lang.UnsatisfiedLinkError: dlopen failed: "libvosk.so" has unexpected e_machine: 40
        at com.sun.jna.Native.open(Native Method)
        at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:204)
        		... 17 more
    	Suppressed: java.lang.UnsatisfiedLinkError: dlopen failed: "/data/app/org.vosk.demo-2/lib/x86/libvosk.so" has unexpected e_machine: 40
        at java.lang.Runtime.loadLibrary(Runtime.java:371)
        at java.lang.System.loadLibrary(System.java:988)
        at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:218)
        		... 17 more
    	Suppressed: java.io.IOException: Native library (android-x86-64/libvosk.so) not found in resource path (.)
        at com.sun.jna.Native.extractFromResourcePath(Native.java:1119)
        at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:275)
        		... 17 more
08-17 19:51:59.325 6059-6059/org.vosk.demo I/Process: Sending signal. PID: 6059 SIG: 9
```
Device:
Moverio BT-300 Smart Glasses
Android 5.1

I can say that it works with version 0.3.17 - ``` implementation 'com.alphacep:vosk-android:0.3.17'.```
Is it possible to fix this?

**Comment by nshmyrev** [comment]
Can you retrieve this file from the filesystem with adb:

/data/app/org.vosk.demo-2/lib/x86/libvosk.so

and check if it has proper architecture. Share the file too. Also check if there is

/data/app/org.vosk.demo-2/lib/x86_64/libvosk.so

**Comment by UsovITAD** [comment]
I found this file in the filesystem (searched through android studio as device is connected directly to computer)

![has_x86](https://user-images.githubusercontent.com/44962742/129848613-b5bbb2e7-a9c4-4852-9c3d-7b58a45d4bc1.PNG)

Also, I found such file in jniLibs in project. I copied it as /x86_64 and /android-x86_64

![add_more](https://user-images.githubusercontent.com/44962742/129849502-7cee935a-bada-46ad-8879-042f03dd1503.PNG)

I tried to upload this file directtly to device here ```/data/app/org.vosk.demo-2/lib/x86_64/libvosk.so``` but got an error

![permission](https://user-images.githubusercontent.com/44962742/129849650-dafee671-d23a-4436-a304-854998b9deae.PNG)

I still get error
```08-18 06:24:03.297 8690-8690/org.vosk.demo E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.vosk.demo, PID: 8690
    java.lang.UnsatisfiedLinkError: Unable to load library 'vosk':
    dlopen failed: "libvosk.so" has unexpected e_machine: 40
    dlopen failed: "libvosk.so" has unexpected e_machine: 40
    dlopen failed: "/data/app/org.vosk.demo-2/lib/x86/libvosk.so" has unexpected e_machine: 40
    Native library (android-x86-64/libvosk.so) not found in resource path (.)
        at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:301)
        at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:461)
        at com.sun.jna.Native.register(Native.java:1746)
        at org.vosk.LibVosk.<clinit>(LibVosk.java:9)
        at org.vosk.demo.VoskActivity.onCreate(VoskActivity.java:72)
        at android.app.Activity.performCreate(Activity.java:5994)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
        at android.app.ActivityThread.access$800(ActivityThread.java:151)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5258)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
    	Suppressed: java.lang.UnsatisfiedLinkError: dlopen failed: "libvosk.so" has unexpected e_machine: 40
        at com.sun.jna.Native.open(Native Method)
        at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:191)
        		... 17 more
    	Suppressed: java.lang.UnsatisfiedLinkError: dlopen failed: "libvosk.so" has unexpected e_machine: 40
        at com.sun.jna.Native.open(Native Method)
        at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:204)
        		... 17 more
    	Suppressed: java.lang.UnsatisfiedLinkError: dlopen failed: "/data/app/org.vosk.demo-2/lib/x86/libvosk.so" has unexpected e_machine: 40
        at java.lang.Runtime.loadLibrary(Runtime.java:371)
        at java.lang.System.loadLibrary(System.java:988)
        at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:218)
        		... 17 more
    	Suppressed: java.io.IOException: Native library (android-x86-64/libvosk.so) not found in resource path (.)
        at com.sun.jna.Native.extractFromResourcePath(Native.java:1119)
        at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:275)
        		... 17 more```

**Comment by nshmyrev** [comment]
> Also, I found such file in jniLibs in project. I copied it as /x86_64 and /android-x86_64

Our demo project doesn't have jniLibs folder like in your screenshot. Are you trying our official demo project or your own project?

> I tried to upload this file directtly to device here /data/app/org.vosk.demo-2/lib/x86_64/libvosk.so but got an error

I asked you to share the folder with me, not to upload it.

**Comment by UsovITAD** [comment]
Okay, I'm sorry, this was another attempt to fix everything. I reimported the project, and now it works. In my project, I use the Jnlibs folder. It looks like this could be a problem for me... I'll check it

**Comment by UsovITAD** [comment]
yeah, it's my fail for now. I didn't notice that there was changed url for repository. Sorry, it's resolved. I'm going to close this issue. Thanks
