### ISSUE TITLE
Android Release apk throw UnsatisfiedLinkError

### ISSUE THREAD

**Issue by mmhmofu** [alphacep/vosk-android-demo#222]
vosk run successfully on debug，but release apk crush.
Error Detail：
java.lang.UnsatisfiedLinkError: Can't obtain class com.sun.jna.Pointer
                                                                                                    	at com.sun.jna.Native.initIDs(Native Method)
                                                                                                    	at com.sun.jna.Native.<clinit>(:7)
                                                                                                    	at com.sun.jna.Native.a()
                                                                                                    	at org.vosk.LibVosk.<clinit>()
                                                                                                    	at org.vosk.LibVosk.vosk_model_new(Native Method)
                                                                                                    	at e.b.a.<init>()
                                                                                                    	at e.b.c.k.a()
                                                                                                    	at e.b.c.f.run(lambda)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                                                    	at java.lang.Thread.run(Thread.java:761)

Dependency already     implementation 'net.java.dev.jna:jna:5.13.0@aar'
    implementation 'com.alphacephei:vosk-android:0.3.47@aar'

**Comment by mmhmofu** [comment]
after  add rule -keep class com.sun.jna.** { *; } in proguard-rules.pro file.it turns to another exception
java.lang.ExceptionInInitializerError
                                                                                                    	at org.vosk.LibVosk.vosk_model_new(Native Method)
                                                                                                    	at e.b.a.<init>()
                                                                                                    	at e.b.c.k.a()
                                                                                                    	at e.b.c.f.run(lambda)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                                                    	at java.lang.Thread.run(Thread.java:761)
                                                                                                    Caused by: java.lang.IllegalArgumentException: Can't create an instance of class e.b.a, requires a public no-arg constructor: java.lang.NoSuchMethodException: <init> []
                                                                                                    	at com.sun.jna.Klass.newInstance()
                                                                                                    	at com.sun.jna.NativeMappedConverter.defaultValue()
                                                                                                    	at com.sun.jna.NativeMappedConverter.<init>()
                                                                                                    	at com.sun.jna.NativeMappedConverter.getInstance()
                                                                                                    	at com.sun.jna.Structure$FFIType.get()
                                                                                                    	at com.sun.jna.Structure$FFIType.get()
                                                                                                    	at com.sun.jna.Native.register()
                                                                                                    	at com.sun.jna.Native.register()
                                                                                                    	at org.vosk.LibVosk.<clinit>()
                                                                                                    	... 7 more
                                                                                                    Caused by: java.lang.NoSuchMethodException: <init> []
                                                                                                    	at java.lang.Class.getConstructor0(Class.java:2204)
                                                                                                    	at java.lang.Class.getDeclaredConstructor(Class.java:2050)
                                                                                                    	... 16 more

**Comment by nshmyrev** [comment]
Hi

You likely need to edit minify project properties to keep required jni files. See here

https://stackoverflow.com/questions/57005617/java-lang-unsatisfiedlinkerror-cant-obtain-class-com-sun-jna-pointer-neurotec

**Comment by mmhmofu** [comment]
> Hi
> 
> You likely need to edit minify project properties to keep required jni files. See here
> 
> https://stackoverflow.com/questions/57005617/java-lang-unsatisfiedlinkerror-cant-obtain-class-com-sun-jna-pointer-neurotec

I already edit proguard-rules.pro file，it turns into another exception 
![QZZ)NM{WE4 %XD}H{8A`6R4](https://github.com/user-attachments/assets/f4b7513c-155c-4e0e-8930-0cbda5a83cc0)

**Comment by mmhmofu** [comment]
> Hi
> 
> You likely need to edit minify project properties to keep required jni files. See here
> 
> https://stackoverflow.com/questions/57005617/java-lang-unsatisfiedlinkerror-cant-obtain-class-com-sun-jna-pointer-neurotec

same question in vosk-android-demo

**Comment by mmhmofu** [comment]
> Hi
> 
> You likely need to edit minify project properties to keep required jni files. See here
> 
> https://stackoverflow.com/questions/57005617/java-lang-unsatisfiedlinkerror-cant-obtain-class-com-sun-jna-pointer-neurotec


should add blew rule both
-keep class com.sun.jna.* { *; }
-keepclassmembers class * extends com.sun.jna.* { public *; }
this can be help,thanks

**Comment by dr0-dev** [comment]
this is not enough, I tried adding it and it still crashes 

Native library (com/sun/jna/android-arm/libjnidispatch.so) not found in resource path (.)

**Comment by mmhmofu** [comment]
> this is not enough, I tried adding it and it still crashes
> 
> Native library (com/sun/jna/android-arm/libjnidispatch.so) not found in resource path (.)

try clean your project and rebuild , check the dependency
